import { SavedLink } from '../types';

export const STARTER_LINKS: Omit<SavedLink, 'id'>[] = [
  // Entertainment
  {
    title: 'YouTube - High Quality Video & Music Hub',
    url: 'https://youtube.com',
    categorySlug: 'entertainment',
    description: 'Favorite video streams, creative essays, podcasts and music playlists.',
    tags: ['streaming', 'music', 'podcasts'],
    isFavorite: true,
    clickCount: 14,
    imageUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=800&auto=format&fit=crop',
    faviconUrl: 'https://www.google.com/s2/favicons?domain=youtube.com&sz=128',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
  },
  {
    title: 'Spotify Web Player - Music for Everyone',
    url: 'https://spotify.com',
    categorySlug: 'entertainment',
    description: 'Focus playlists, ambient audio, albums and weekly discovery.',
    tags: ['music', 'audio'],
    isFavorite: false,
    clickCount: 8,
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop',
    faviconUrl: 'https://www.google.com/s2/favicons?domain=spotify.com&sz=128',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },

  // Study
  {
    title: 'MIT OpenCourseWare - Free Online Course Materials',
    url: 'https://ocw.mit.edu',
    categorySlug: 'study',
    description: 'Comprehensive curriculum, lecture notes, video lectures, and exams from MIT.',
    tags: ['mit', 'education', 'computer-science'],
    isFavorite: true,
    clickCount: 23,
    imageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=800&auto=format&fit=crop',
    faviconUrl: 'https://www.google.com/s2/favicons?domain=ocw.mit.edu&sz=128',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
  },
  {
    title: 'GitHub - Code Collaboration & Open Source',
    url: 'https://github.com',
    categorySlug: 'study',
    description: 'Open source repositories, personal projects, issue tracking, and developer libraries.',
    tags: ['coding', 'git', 'development'],
    isFavorite: true,
    clickCount: 41,
    imageUrl: 'https://opengraph.githubassets.com/1/torvalds/linux',
    faviconUrl: 'https://github.githubassets.com/favicons/favicon.svg',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
  },
  {
    title: 'arXiv.org - Open Access Scientific Papers',
    url: 'https://arxiv.org',
    categorySlug: 'study',
    description: 'Preprints in Physics, Mathematics, Computer Science, Quantitative Biology and AI.',
    tags: ['research', 'papers', 'ai'],
    isFavorite: false,
    clickCount: 5,
    imageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?q=80&w=800&auto=format&fit=crop',
    faviconUrl: 'https://www.google.com/s2/favicons?domain=arxiv.org&sz=128',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 1,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 1,
  },

  // Information
  {
    title: 'Wikipedia - The Free Encyclopedia',
    url: 'https://en.wikipedia.org',
    categorySlug: 'information',
    description: 'Comprehensive open-access collaborative reference encyclopedia.',
    tags: ['reference', 'encyclopedia', 'knowledge'],
    isFavorite: true,
    clickCount: 19,
    imageUrl: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?q=80&w=800&auto=format&fit=crop',
    faviconUrl: 'https://www.google.com/s2/favicons?domain=en.wikipedia.org&sz=128',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
  },
  {
    title: 'Hacker News - Technology & Computing Discourse',
    url: 'https://news.ycombinator.com',
    categorySlug: 'information',
    description: 'Curated tech industry news, engineering developments, and startup analysis.',
    tags: ['tech', 'news', 'industry'],
    isFavorite: false,
    clickCount: 12,
    imageUrl: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?q=80&w=800&auto=format&fit=crop',
    faviconUrl: 'https://www.google.com/s2/favicons?domain=news.ycombinator.com&sz=128',
    createdAt: Date.now() - 1000 * 60 * 60 * 12,
    updatedAt: Date.now() - 1000 * 60 * 60 * 12,
  },
];
